# 1 Pandas高级数据处理

In [1]:
import numpy as np
import pandas as pd

## 1.1级联
汇总全年的销售数据

In [2]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df1

   A  B
0  1  4
1  2  5
2  3  6

In [3]:
df2 = pd.DataFrame({'A':[9,8,7],'B':[10,11,12]})
df2

   A   B
0  9  10
1  8  11
2  7  12

In [4]:
pd.concat([df1,df2],ignore_index=True,axis=0,verify_integrity=True)

   A   B
0  1   4
1  2   5
2  3   6
3  9  10
4  8  11
5  7  12

In [5]:
df3 = pd.DataFrame(np.random.randint(0,100,size=(3,3)),columns=['A','B','C'])
df4 = pd.DataFrame(np.random.randint(0,100,size=(3,3)),columns=['C','D','B'])
display(df3)
display(df4)

    A   B   C
0  61  28  42
1  86  71  69
2  80  80  34

    C   D   B
0  39  93  47
1  10  68  40
2  14  40  89

In [6]:
# 没有的列填充空值。
pd.concat([df3,df4],ignore_index=True,axis=0,verify_integrity=True)

      A   B   C     D
0  61.0  28  42   NaN
1  86.0  71  69   NaN
2  80.0  80  34   NaN
3   NaN  47  39  93.0
4   NaN  40  10  68.0
5   NaN  89  14  40.0

In [7]:
# inner就是内联，相当于sql里面的inner join，默认是outer，相当于sql里面的full join
pd.concat([df3,df4],ignore_index=True,axis=0,verify_integrity=True,join='inner')

    B   C
0  28  42
1  71  69
2  80  34
3  47  39
4  40  10
5  89  14

In [8]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# ======================
# 1. 学生基本信息表 (df1)
# ======================
np.random.seed(42)  # 保证数据可复现
student_base = {
    '学号': [f'S{datetime.now().year}00{i}' for i in range(1, 11)],
    '姓名': ['张三', '李四', '王五', '赵六', '钱七', '孙八', '周九', '吴十', '郑十一', '王十二'],
    '年龄': np.random.randint(18, 25, 10),
    '班级': ['一班', '二班', '三班', '四班', '五班', '六班', '七班', '八班', '九班', '十班'],
    '专业': ['计算机科学', '电子信息', '机械工程', '数学', '物理', '化学', '生物', '金融', '会计', '法学'],
    '入学日期': [datetime(2023, 9, 1) + timedelta(days=i*3) for i in range(10)],
    '性别': np.random.choice(['男', '女'], 10, p=[0.6, 0.4]),
    '手机号': [f'138{np.random.randint(100000000, 999999999)}' for _ in range(10)],
    '家庭住址': ['北京市海淀区', '上海市浦东新区', '广州市天河区', '深圳市南山区', '杭州市西湖区', 
                '成都市武侯区', '武汉市江汉区', '南京市玄武区', '西安市雁塔区', '长沙市岳麓区']
}

df1 = pd.DataFrame(student_base)
df1['入学日期'] = pd.to_datetime(df1['入学日期']).dt.strftime('%Y-%m-%d')  # 格式化日期

# ======================
# 2. 学生成绩表 (df2)
# ======================
scores = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七', '孙八', '周九', '吴十', '郑十一', '王十二'],
    '语文': np.random.randint(60, 100, 10),
    '数学': np.random.randint(60, 100, 10),
    '英语': np.random.randint(60, 100, 10),
    '物理': np.random.randint(60, 100, 10),
    '化学': np.random.randint(60, 100, 10),
    '总分': [np.random.randint(300, 500) for _ in range(10)],
    '绩点': np.round(np.random.uniform(2.0, 4.0, 10), 2),
    '成绩等级': np.random.choice(['优秀', '良好', '中等', '及格', '不及格'], 10, p=[0.3, 0.4, 0.2, 0.08, 0.02])
}

df2 = pd.DataFrame(scores)

# ======================
# 3. 学生城市信息表 (df3)
# ======================
city_info = {
    '城市': ['北京', '上海', '广州', '深圳', '杭州', '成都', '武汉', '南京', '西安', '长沙'],
    '省份': ['北京', '上海', '广东', '广东', '浙江', '四川', '湖北', '江苏', '陕西', '湖南'],
    '邮编': ['100000', '200000', '510000', '518000', '310000', '610000', '430000', '210000', '710000', '410000'],
    '人口(万)': [2154, 2418, 1874, 1756, 1036, 1633, 1365, 850, 1297, 1000],
    '城市面积(平方公里)': [16410.5, 6340.5, 7434.4, 1997.4, 16596.0, 14174.0, 8494.0, 6587.0, 10752.0, 11819.0],
    '交通指数': [8.7, 9.2, 7.5, 8.3, 8.0, 7.8, 7.2, 7.6, 6.9, 7.4]
}

df3 = pd.DataFrame(city_info)
df3 = df3.set_index('城市')  # 为join操作设置索引

# ======================
# 4. 学生兴趣信息表 (df4)
# ======================
interests = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七', '孙八', '周九', '吴十', '陈九', '刘十'],
    '兴趣': ['篮球', '足球', '乒乓球', '游泳', '编程', '摄影', '音乐', '绘画', '舞蹈', '阅读'],
    '兴趣详情': [
        '校队主力，每周3次训练',
        '校队替补，每周2次训练',
        '俱乐部成员，每周4次训练',
        '市级比赛选手，每周5次训练',
        '个人项目，自学3年',
        '专业摄影，参加省级比赛',
        '自学钢琴，参加市级演出',
        '专业绘画，作品参展',
        '专业舞蹈，省级比赛获奖',
        '阅读爱好者，年均50本书'
    ],
    '开始时间': [datetime(2022, 3, 15) + timedelta(days=i*30) for i in range(10)],
    '兴趣等级': np.random.choice(['高级', '中级', '初级'], 10, p=[0.4, 0.4, 0.2]),
    '报名状态': np.random.choice(['已报名', '未报名'], 10, p=[0.7, 0.3])
}

df4 = pd.DataFrame(interests)
df4['开始时间'] = pd.to_datetime(df4['开始时间']).dt.strftime('%Y-%m-%d')

# ======================
# 5. 学生家庭信息表 (df5)
# ======================
family = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七', '孙八', '周九', '吴十', '郑十一', '王十二'],
    '父亲职业': ['工程师', '教师', '医生', '程序员', '律师', '设计师', '公务员', '教师', '医生', '工程师'],
    '母亲职业': ['教师', '医生', '工程师', '设计师', '律师', '公务员', '教师', '工程师', '医生', '设计师'],
    '家庭年收入(万元)': np.random.randint(15, 100, 10),
    '是否独生子女': np.random.choice([True, False], 10, p=[0.6, 0.4]),
    '家庭住址': ['北京市海淀区', '上海市浦东新区', '广州市天河区', '深圳市南山区', '杭州市西湖区', 
                '成都市武侯区', '武汉市江汉区', '南京市玄武区', '西安市雁塔区', '长沙市岳麓区']
}

df5 = pd.DataFrame(family)

# ======================
# 打印所有表格结构（方便查看）
print("===== 学生基本信息表 (df1) =====")
print(df1.head(3))
print("\n===== 学生成绩表 (df2) =====")
print(df2.head(3))
print("\n===== 学生城市信息表 (df3) =====")
print(df3.head(3))
print("\n===== 学生兴趣信息表 (df4) =====")
print(df4.head(3))
print("\n===== 学生家庭信息表 (df5) =====")
print(df5.head(3))

===== 学生基本信息表 (df1) =====
         学号  姓名  年龄  班级     专业        入学日期 性别           手机号     家庭住址
0  S2026001  张三  24  一班  计算机科学  2023-09-01  男  138604579232   北京市海淀区
1  S2026002  李四  21  二班   电子信息  2023-09-04  男  138332968651  上海市浦东新区
2  S2026003  王五  22  三班   机械工程  2023-09-07  男  138579546681   广州市天河区

===== 学生成绩表 (df2) =====
   姓名  语文  数学  英语  物理  化学   总分    绩点 成绩等级
0  张三  87  63  94  77  82  344  2.40   良好
1  李四  75  84  73  85  99  364  3.42   良好
2  王五  74  73  76  93  80  388  3.58   良好

===== 学生城市信息表 (df3) =====
    省份      邮编  人口(万)  城市面积(平方公里)  交通指数
城市
北京  北京  100000   2154     16410.5   8.7
上海  上海  200000   2418      6340.5   9.2
广州  广东  510000   1874      7434.4   7.5

===== 学生兴趣信息表 (df4) =====
   姓名   兴趣          兴趣详情        开始时间 兴趣等级 报名状态
0  张三   篮球   校队主力，每周3次训练  2022-03-15   高级  已报名
1  李四   足球   校队替补，每周2次训练  2022-04-14   高级  已报名
2  王五  乒乓球  俱乐部成员，每周4次训练  2022-05-14   高级  已报名

===== 学生家庭信息表 (df5) =====
   姓名 父亲职业 母亲职业  家庭年收入(万元)  是否独生子女     家庭住址
0  张三  工程师   教师         76    True   北京市海淀区
1  李四   教师   医生         71    True  上海市浦东新区
2  王五   医生  工程师         20    True   广州市天河区

In [9]:
display(df1,df2,df3,df4,df5)

          学号   姓名  年龄  班级     专业        入学日期 性别           手机号     家庭住址
0   S2026001   张三  24  一班  计算机科学  2023-09-01  男  138604579232   北京市海淀区
1   S2026002   李四  21  二班   电子信息  2023-09-04  男  138332968651  上海市浦东新区
2   S2026003   王五  22  三班   机械工程  2023-09-07  男  138579546681   广州市天河区
3   S2026004   赵六  24  四班     数学  2023-09-10  男  138206328085   深圳市南山区
4   S2026005   钱七  20  五班     物理  2023-09-13  女  138130349564   杭州市西湖区
5   S2026006   孙八  22  六班     化学  2023-09-16  男  138881447915   成都市武侯区
6   S2026007   周九  22  七班     生物  2023-09-19  女  138199052376   武汉市江汉区
7   S2026008   吴十  24  八班     金融  2023-09-22  女  138277077808   南京市玄武区
8   S2026009  郑十一  19  九班     会计  2023-09-25  男  138206406362   西安市雁塔区
9  S20260010  王十二  20  十班     法学  2023-09-28  女  138580404538   长沙市岳麓区

    姓名  语文  数学  英语  物理  化学   总分    绩点 成绩等级
0   张三  87  63  94  77  82  344  2.40   良好
1   李四  75  84  73  85  99  364  3.42   良好
2   王五  74  73  76  93  80  388  3.58   良好
3   赵六  62  68  95  69  75  370  3.21   良好
4   钱七  96  85  99  95  77  308  3.85   优秀
5   孙八  66  61  63  73  83  387  3.30   良好
6   周九  80  79  61  90  85  428  3.83   良好
7   吴十  68  87  65  74  84  435  3.70   及格
8  郑十一  98  66  63  67  88  362  2.90   中等
9  王十二  77  67  88  73  74  438  2.19   中等

    省份      邮编  人口(万)  城市面积(平方公里)  交通指数
城市
北京  北京  100000   2154     16410.5   8.7
上海  上海  200000   2418      6340.5   9.2
广州  广东  510000   1874      7434.4   7.5
深圳  广东  518000   1756      1997.4   8.3
杭州  浙江  310000   1036     16596.0   8.0
成都  四川  610000   1633     14174.0   7.8
武汉  湖北  430000   1365      8494.0   7.2
南京  江苏  210000    850      6587.0   7.6
西安  陕西  710000   1297     10752.0   6.9
长沙  湖南  410000   1000     11819.0   7.4

   姓名   兴趣           兴趣详情        开始时间 兴趣等级 报名状态
0  张三   篮球    校队主力，每周3次训练  2022-03-15   高级  已报名
1  李四   足球    校队替补，每周2次训练  2022-04-14   高级  已报名
2  王五  乒乓球   俱乐部成员，每周4次训练  2022-05-14   高级  已报名
3  赵六   游泳  市级比赛选手，每周5次训练  2022-06-13   中级  已报名
4  钱七   编程      个人项目，自学3年  2022-07-13   高级  已报名
5  孙八   摄影    专业摄影，参加省级比赛  2022-08-12   中级  未报名
6  周九   音乐    自学钢琴，参加市级演出  2022-09-11   高级  已报名
7  吴十   绘画      专业绘画，作品参展  2022-10-11   初级  已报名
8  陈九   舞蹈    专业舞蹈，省级比赛获奖  2022-11-10   中级  未报名
9  刘十   阅读   阅读爱好者，年均50本书  2022-12-10   中级  已报名

    姓名 父亲职业 母亲职业  家庭年收入(万元)  是否独生子女     家庭住址
0   张三  工程师   教师         76    True   北京市海淀区
1   李四   教师   医生         71    True  上海市浦东新区
2   王五   医生  工程师         20    True   广州市天河区
3   赵六  程序员  设计师         42   False   深圳市南山区
4   钱七   律师   律师         42    True   杭州市西湖区
5   孙八  设计师  公务员         58   False   成都市武侯区
6   周九  公务员   教师         98    True   武汉市江汉区
7   吴十   教师  工程师         44    True   南京市玄武区
8  郑十一   医生   医生         76    True   西安市雁塔区
9  王十二  工程师  设计师         89    True   长沙市岳麓区

### 1.2.1计算男生和女生的平均绩点
参数：left，on，right，on

In [10]:
data1 = df1.merge(df2,on='姓名',how='left')
data1

,学号,姓名,年龄,班级,专业,入学日期,性别,手机号,家庭住址,语文,数学,英语,物理,化学,总分,绩点,成绩等级
0,S2026001,张三,24,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区,87,63,94,77,82,344,2.40,良好
1,S2026002,李四,21,二班,电子信息,2023-09-04,男,138332968651,上海市浦东新区,75,84,73,85,99,364,3.42,良好
2,S2026003,王五,22,三班,机械工程,2023-09-07,男,138579546681,广州市天河区,74,73,76,93,80,388,3.58,良好
3,S2026004,赵六,24,四班,数学,2023-09-10,男,138206328085,深圳市南山区,62,68,95,69,75,370,3.21,良好
4,S2026005,钱七,20,五班,物理,2023-09-13,女,138130349564,杭州市西湖区,96,85,99,95,77,308,3.85,优秀
5,S2026006,孙八,22,六班,化学,2023-09-16,男,138881447915,成都市武侯区,66,61,63,73,83,387,3.30,良好
6,S2026007,周九,22,七班,生物,2023-09-19,女,138199052376,武汉市江汉区,80,79,61,90,85,428,3.83,良好
7,S2026008,吴十,24,八班,金融,2023-09-22,女,138277077808,南京市玄武区,68,87,65,74,84,435,3.70,及格
8,S2026009,郑十一,19,九班,会计,2023-09-25,男,138206406362,西安市雁塔区,98,66,63,67,88,362,2.90,中等
9,S20260010,王十二,20,十班,法学,2023-09-28,女,138580404538,长沙市岳麓区,77,67,88,73,74,438,2.19,中等

In [11]:
display(data1.query('性别=="男"')['绩点'].mean())
display(data1.query('性别=="女"')['绩点'].mean())

np.float64(3.135)

np.float64(3.3924999999999996)

## 1.2.2 获取绩点高于平均绩点的学生，查看其家庭的平均年薪比绩点低于平均绩点的学生的家庭平均年薪高多少倍
参数how

In [12]:
data1 = df2.merge(df5,how='left')
data1

,姓名,语文,数学,英语,物理,化学,总分,绩点,成绩等级,父亲职业,母亲职业,家庭年收入(万元),是否独生子女,家庭住址
0,张三,87,63,94,77,82,344,2.40,良好,工程师,教师,76,True,北京市海淀区
1,李四,75,84,73,85,99,364,3.42,良好,教师,医生,71,True,上海市浦东新区
2,王五,74,73,76,93,80,388,3.58,良好,医生,工程师,20,True,广州市天河区
3,赵六,62,68,95,69,75,370,3.21,良好,程序员,设计师,42,False,深圳市南山区
4,钱七,96,85,99,95,77,308,3.85,优秀,律师,律师,42,True,杭州市西湖区
5,孙八,66,61,63,73,83,387,3.30,良好,设计师,公务员,58,False,成都市武侯区
6,周九,80,79,61,90,85,428,3.83,良好,公务员,教师,98,True,武汉市江汉区
7,吴十,68,87,65,74,84,435,3.70,及格,教师,工程师,44,True,南京市玄武区
8,郑十一,98,66,63,67,88,362,2.90,中等,医生,医生,76,True,西安市雁塔区
9,王十二,77,67,88,73,74,438,2.19,中等,工程师,设计师,89,True,长沙市岳麓区

In [13]:
data1['平均绩点']=data1['绩点'].mean()
data1

,姓名,语文,数学,英语,物理,化学,总分,绩点,成绩等级,父亲职业,母亲职业,家庭年收入(万元),是否独生子女,家庭住址,平均绩点
0,张三,87,63,94,77,82,344,2.40,良好,工程师,教师,76,True,北京市海淀区,3.238
1,李四,75,84,73,85,99,364,3.42,良好,教师,医生,71,True,上海市浦东新区,3.238
2,王五,74,73,76,93,80,388,3.58,良好,医生,工程师,20,True,广州市天河区,3.238
3,赵六,62,68,95,69,75,370,3.21,良好,程序员,设计师,42,False,深圳市南山区,3.238
4,钱七,96,85,99,95,77,308,3.85,优秀,律师,律师,42,True,杭州市西湖区,3.238
5,孙八,66,61,63,73,83,387,3.30,良好,设计师,公务员,58,False,成都市武侯区,3.238
6,周九,80,79,61,90,85,428,3.83,良好,公务员,教师,98,True,武汉市江汉区,3.238
7,吴十,68,87,65,74,84,435,3.70,及格,教师,工程师,44,True,南京市玄武区,3.238
8,郑十一,98,66,63,67,88,362,2.90,中等,医生,医生,76,True,西安市雁塔区,3.238
9,王十二,77,67,88,73,74,438,2.19,中等,工程师,设计师,89,True,长沙市岳麓区,3.238

In [14]:
display(data1[data1['绩点']>data1['平均绩点']]['家庭年收入(万元)'].mean())
display(data1[data1['绩点']<data1['平均绩点']]['家庭年收入(万元)'].mean())

np.float64(55.5)

np.float64(70.75)

### 1.2.3 找出男生和女生有相同的年龄的
参数解释：on，suffixes
- 一个男生和一个女生有相同的年龄的

In [15]:
data1 = df1.merge(df1,how='left',on=['年龄'])
data1

,学号_x,姓名_x,年龄,班级_x,专业_x,入学日期_x,性别_x,手机号_x,家庭住址_x,学号_y,姓名_y,班级_y,专业_y,入学日期_y,性别_y,手机号_y,家庭住址_y
0,S2026001,张三,24,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区,S2026001,张三,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区
1,S2026001,张三,24,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区,S2026004,赵六,四班,数学,2023-09-10,男,138206328085,深圳市南山区
2,S2026001,张三,24,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区,S2026008,吴十,八班,金融,2023-09-22,女,138277077808,南京市玄武区
3,S2026002,李四,21,二班,电子信息,2023-09-04,男,138332968651,上海市浦东新区,S2026002,李四,二班,电子信息,2023-09-04,男,138332968651,上海市浦东新区
4,S2026003,王五,22,三班,机械工程,2023-09-07,男,138579546681,广州市天河区,S2026003,王五,三班,机械工程,2023-09-07,男,138579546681,广州市天河区
5,S2026003,王五,22,三班,机械工程,2023-09-07,男,138579546681,广州市天河区,S2026006,孙八,六班,化学,2023-09-16,男,138881447915,成都市武侯区
6,S2026003,王五,22,三班,机械工程,2023-09-07,男,138579546681,广州市天河区,S2026007,周九,七班,生物,2023-09-19,女,138199052376,武汉市江汉区
7,S2026004,赵六,24,四班,数学,2023-09-10,男,138206328085,深圳市南山区,S2026001,张三,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区
8,S2026004,赵六,24,四班,数学,2023-09-10,男,138206328085,深圳市南山区,S2026004,赵六,四班,数学,2023-09-10,男,138206328085,深圳市南山区
9,S2026004,赵六,24,四班,数学,2023-09-10,男,138206328085,深圳市南山区,S2026008,吴十,八班,金融,2023-09-22,女,138277077808,南京市玄武区
10,S2026005,钱七,20,五班,物理,2023-09-13,女,138130349564,杭州市西湖区,S2026005,钱七,五班,物理,2023-09-13,女,138130349564,杭州市西湖区
11,S2026005,钱七,20,五班,物理,2023-09-13,女,138130349564,杭州市西湖区,S20260010,王十二,十班,法学,2023-09-28,女,138580404538,长沙市岳麓区
12,S2026006,孙八,22,六班,化学,2023-09-16,男,138881447915,成都市武侯区,S2026003,王五,三班,机械工程,2023-09-07,男,138579546681,广州市天河区
13,S2026006,孙八,22,六班,化学,2023-09-16,男,138881447915,成都市武侯区,S2026006,孙八,六班,化学,2023-09-16,男,138881447915,成都市武侯区
14,S2026006,孙八,22,六班,化学,2023-09-16,男,138881447915,成都市武侯区,S2026007,周九,七班,生物,2023-09-19,女,138199052376,武汉市江汉区
15,S2026007,周九,22,七班,生物,2023-09-19,女,138199052376,武汉市江汉区,S2026003,王五,三班,机械工程,2023-09-07,男,138579546681,广州市天河区
16,S2026007,周九,22,七班,生物,2023-09-19,女,138199052376,武汉市江汉区,S2026006,孙八,六班,化学,2023-09-16,男,138881447915,成都市武侯区
17,S2026007,周九,22,七班,生物,2023-09-19,女,138199052376,武汉市江汉区,S2026007,周九,七班,生物,2023-09-19,女,138199052376,武汉市江汉区
18,S2026008,吴十,24,八班,金融,2023-09-22,女,138277077808,南京市玄武区,S2026001,张三,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区
19,S2026008,吴十,24,八班,金融,2023-09-22,女,138277077808,南京市玄武区,S2026004,赵六,四班,数学,2023-09-10,男,138206328085,深圳市南山区
20,S2026008,吴十,24,八班,金融,2023-09-22,女,138277077808,南京市玄武区,S2026008,吴十,八班,金融,2023-09-22,女,138277077808,南京市玄武区
21,S2026009,郑十一,19,九班,会计,2023-09-25,男,138206406362,西安市雁塔区,S2026009,郑十一,九班,会计,2023-09-25,男,138206406362,西安市雁塔区
22,S20260010,王十二,20,十班,法学,2023-09-28,女,138580404538,长沙市岳麓区,S2026005,钱七,五班,物理,2023-09-13,女,138130349564,杭州市西湖区
23,S20260010,王十二,20,十班,法学,2023-09-28,女,138580404538,长沙市岳麓区,S20260010,王十二,十班,法学,2023-09-28,女,138580404538,长沙市岳麓区

In [16]:
data1.loc[data1['性别_x']!=data1['性别_y']].drop_duplicates(subset=['姓名_x'])

,学号_x,姓名_x,年龄,班级_x,专业_x,入学日期_x,性别_x,手机号_x,家庭住址_x,学号_y,姓名_y,班级_y,专业_y,入学日期_y,性别_y,手机号_y,家庭住址_y
2,S2026001,张三,24,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区,S2026008,吴十,八班,金融,2023-09-22,女,138277077808,南京市玄武区
6,S2026003,王五,22,三班,机械工程,2023-09-07,男,138579546681,广州市天河区,S2026007,周九,七班,生物,2023-09-19,女,138199052376,武汉市江汉区
9,S2026004,赵六,24,四班,数学,2023-09-10,男,138206328085,深圳市南山区,S2026008,吴十,八班,金融,2023-09-22,女,138277077808,南京市玄武区
14,S2026006,孙八,22,六班,化学,2023-09-16,男,138881447915,成都市武侯区,S2026007,周九,七班,生物,2023-09-19,女,138199052376,武汉市江汉区
15,S2026007,周九,22,七班,生物,2023-09-19,女,138199052376,武汉市江汉区,S2026003,王五,三班,机械工程,2023-09-07,男,138579546681,广州市天河区
18,S2026008,吴十,24,八班,金融,2023-09-22,女,138277077808,南京市玄武区,S2026001,张三,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区

In [17]:
# 上下拼接
total = pd.concat([df1,df2])
total

,学号,姓名,年龄,班级,专业,入学日期,性别,手机号,家庭住址,语文,数学,英语,物理,化学,总分,绩点,成绩等级
0,S2026001,张三,24.0,一班,计算机科学,2023-09-01,男,138604579232,北京市海淀区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,S2026002,李四,21.0,二班,电子信息,2023-09-04,男,138332968651,上海市浦东新区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,S2026003,王五,22.0,三班,机械工程,2023-09-07,男,138579546681,广州市天河区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,S2026004,赵六,24.0,四班,数学,2023-09-10,男,138206328085,深圳市南山区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,S2026005,钱七,20.0,五班,物理,2023-09-13,女,138130349564,杭州市西湖区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,S2026006,孙八,22.0,六班,化学,2023-09-16,男,138881447915,成都市武侯区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,S2026007,周九,22.0,七班,生物,2023-09-19,女,138199052376,武汉市江汉区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,S2026008,吴十,24.0,八班,金融,2023-09-22,女,138277077808,南京市玄武区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,S2026009,郑十一,19.0,九班,会计,2023-09-25,男,138206406362,西安市雁塔区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,S20260010,王十二,20.0,十班,法学,2023-09-28,女,138580404538,长沙市岳麓区,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,张三,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,63.0,94.0,77.0,82.0,344.0,2.40,良好
1,NaN,李四,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,84.0,73.0,85.0,99.0,364.0,3.42,良好
2,NaN,王五,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.0,73.0,76.0,93.0,80.0,388.0,3.58,良好
3,NaN,赵六,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,68.0,95.0,69.0,75.0,370.0,3.21,良好
4,NaN,钱七,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.0,85.0,99.0,95.0,77.0,308.0,3.85,优秀
5,NaN,孙八,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66.0,61.0,63.0,73.0,83.0,387.0,3.30,良好
6,NaN,周九,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,79.0,61.0,90.0,85.0,428.0,3.83,良好
7,NaN,吴十,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,87.0,65.0,74.0,84.0,435.0,3.70,及格
8,NaN,郑十一,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,66.0,63.0,67.0,88.0,362.0,2.90,中等
9,NaN,王十二,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,67.0,88.0,73.0,74.0,438.0,2.19,中等

## 1.3 分组
1. 分组必聚合
- grouopby()

In [18]:
data =  pd.read_csv('canyin2019.csv')
data

     V1  V2    V3    V4     V5    V6      V7      V8      V9
0    北京  95  6114  16.3  240.8  68.4  480.42  174.29  152.28
1    天津   9   813   3.5   25.9   7.8   49.54   21.88    5.13
2    河北   5    23   0.1    4.1   0.7    2.52    1.60    0.61
3    山西   4   110   0.5    4.1   1.2    7.52    3.85    3.63
4   内蒙古   3   111   0.3    6.5   0.7   18.27   16.08    0.12
5    辽宁  13   996   1.6   35.6  12.8   65.81   58.14   52.85
6   黑龙江   4    79   0.2    2.9   0.9    3.92    1.36    1.20
7    江苏  18  1798   5.6   52.2  16.8  122.30   59.43   23.56
8    浙江  31  2028   4.9   68.3  22.1  137.91   44.65   34.52
9    安徽   8   738   1.7   19.9   5.8   33.04    9.91    9.77
10   福建  23   821   3.0   25.3   7.5   45.71   15.55   11.68
11   江西   4   177   0.4    6.1   2.0   11.33    7.05    6.89
12   山东  17   749   2.2   43.2  11.1   68.55   17.91   15.68
13   河南  14   273   0.7    8.7   4.6   13.79    4.66    3.33
14   湖北  34  1601   3.4   50.4  13.6   90.81   27.40   22.01
15   湖南  18  1023   4.2   53.7  22.8   56.60   18.61   16.10
16   广西   4   381   1.0    7.9   2.5   16.56    4.53    4.53
17   海南   1     8   0.0    0.3   0.1    1.01    0.28    0.28
18   重庆  12  1279   4.1   64.7  18.5   81.80   25.74   12.84
19   四川  10  1486   5.6   54.3  20.3  107.28   19.98   13.01
20   贵州   2    16   0.0    1.7   0.3    0.56    0.22    0.22
21   云南   5   258   0.7    5.6   2.8   14.58    4.65    2.83
22   西藏   1     6   0.0    0.1   0.1    0.67    0.15    0.15
23   陕西  10   475   1.6   15.9   8.9   29.60   10.36   10.30
24   甘肃   3    67   0.3    2.1   0.6    4.09    1.86    1.86
25   新疆   5   144   0.3    4.0   1.3    6.70    2.73    2.73
26   上海  63  7008  15.9  174.8  48.9  399.25  107.04   62.69
27   广东  79  5774  15.4  172.4  43.7  364.35  114.40   92.82

In [19]:
data.groupby('V1')['V2'].mean()

V1
上海     63.0
云南      5.0
内蒙古     3.0
北京     95.0
四川     10.0
天津      9.0
安徽      8.0
山东     17.0
山西      4.0
广东     79.0
广西      4.0
新疆      5.0
江苏     18.0
江西      4.0
河北      5.0
河南     14.0
浙江     31.0
海南      1.0
湖北     34.0
湖南     18.0
甘肃      3.0
福建     23.0
西藏      1.0
贵州      2.0
辽宁     13.0
重庆     12.0
陕西     10.0
黑龙江     4.0
Name: V2, dtype: float64

In [20]:
# 聚合多个字段的
data.groupby('V1').agg({'V2':np.sum})

C:\Users\35796\AppData\Local\Temp\ipykernel_32232\4173935211.py:2: FutureWarning: The provided callable <function sum at 0x00000000092DEB60> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  data.groupby('V1').agg({'V2':np.sum})

     V2
V1
上海   63
云南    5
内蒙古   3
北京   95
四川   10
天津    9
安徽    8
山东   17
山西    4
广东   79
广西    4
新疆    5
江苏   18
江西    4
河北    5
河南   14
浙江   31
海南    1
湖北   34
湖南   18
甘肃    3
福建   23
西藏    1
贵州    2
辽宁   13
重庆   12
陕西   10
黑龙江   4

In [21]:
data.groupby('V1')['V2'].apply(np.mean)

V1
上海     63.0
云南      5.0
内蒙古     3.0
北京     95.0
四川     10.0
天津      9.0
安徽      8.0
山东     17.0
山西      4.0
广东     79.0
广西      4.0
新疆      5.0
江苏     18.0
江西      4.0
河北      5.0
河南     14.0
浙江     31.0
海南      1.0
湖北     34.0
湖南     18.0
甘肃      3.0
福建     23.0
西藏      1.0
贵州      2.0
辽宁     13.0
重庆     12.0
陕西     10.0
黑龙江     4.0
Name: V2, dtype: float64

In [22]:
data['V2'].apply(lambda x:'贵' if x>10 else '便宜')

0      贵
1     便宜
2     便宜
3     便宜
4     便宜
5      贵
6     便宜
7      贵
8      贵
9     便宜
10     贵
11    便宜
12     贵
13     贵
14     贵
15     贵
16    便宜
17    便宜
18     贵
19    便宜
20    便宜
21    便宜
22    便宜
23    便宜
24    便宜
25    便宜
26     贵
27     贵
Name: V2, dtype: object

## 1.4 交叉表
统计的是频次

In [23]:
pd.crosstab(data['V1'],data['V2'])

V2,1,2,3,4,5,8,9,10,12,13,14,17,18,23,31,34,63,79,95
V1,,,,,,,,,,,,,,,,,,,
上海,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
云南,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
内蒙古,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
北京,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
四川,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
天津,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
安徽,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
山东,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
山西,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
广东,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
广西,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
新疆,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
江苏,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
江西,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
河北,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
河南,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
浙江,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
海南,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
湖北,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
湖南,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
甘肃,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
福建,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
西藏,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
贵州,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
辽宁,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
重庆,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
陕西,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
黑龙江,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## 1.5 透视表
透视表和交叉表的区别就是，透视表不只是统计频次，还可以统计其他的指标，比如均值、中位数、标准差等。

In [24]:
pd.pivot_table(data=data,index='V1',columns='V2',values='V3',aggfunc=np.mean)

C:\Users\35796\AppData\Local\Temp\ipykernel_32232\1623358576.py:1: FutureWarning: The provided callable <function mean at 0x00000000092DFF60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(data=data,index='V1',columns='V2',values='V3',aggfunc=np.mean)

V2,1,2,3,4,5,8,9,10,12,13,14,17,18,23,31,34,63,79,95
V1,,,,,,,,,,,,,,,,,,,
上海,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7008.0,NaN,NaN
云南,NaN,NaN,NaN,NaN,258.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
内蒙古,NaN,NaN,111.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
北京,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6114.0
四川,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1486.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
天津,NaN,NaN,NaN,NaN,NaN,NaN,813.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
安徽,NaN,NaN,NaN,NaN,NaN,738.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
山东,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,749.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
山西,NaN,NaN,NaN,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
广东,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5774.0,NaN
广西,NaN,NaN,NaN,381.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
新疆,NaN,NaN,NaN,NaN,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
江苏,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1798.0,NaN,NaN,NaN,NaN,NaN,NaN
江西,NaN,NaN,NaN,177.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
河北,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
河南,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,273.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
浙江,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2028.0,NaN,NaN,NaN,NaN
海南,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
湖北,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1601.0,NaN,NaN,NaN
湖南,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1023.0,NaN,NaN,NaN,NaN,NaN,NaN
甘肃,NaN,NaN,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
福建,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,821.0,NaN,NaN,NaN,NaN,NaN
西藏,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
贵州,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
辽宁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,996.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
重庆,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1279.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
陕西,NaN,NaN,NaN,NaN,NaN,NaN,NaN,475.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
黑龙江,NaN,NaN,NaN,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 1.6 查找（isin）
查找多个值的

In [25]:
data.loc[data['V2'].isin([95,23])]

    V1  V2    V3    V4     V5    V6      V7      V8      V9
0   北京  95  6114  16.3  240.8  68.4  480.42  174.29  152.28
10  福建  23   821   3.0   25.3   7.5   45.71   15.55   11.68

## 1.7 区间划分（cut）

In [26]:
data['V3'].map(lambda x: '高' if x>100 else '低')

0     高
1     高
2     低
3     高
4     高
5     高
6     低
7     高
8     高
9     高
10    高
11    高
12    高
13    高
14    高
15    高
16    高
17    低
18    高
19    高
20    低
21    高
22    低
23    高
24    低
25    高
26    高
27    高
Name: V3, dtype: object

In [27]:
bins = [data['V2'].min()-1,10,20,30,40,50,data['V2'].max()]
pd.cut(data['V2'],bins=bins,right=False)

0              NaN
1      [0.0, 10.0)
2      [0.0, 10.0)
3      [0.0, 10.0)
4      [0.0, 10.0)
5     [10.0, 20.0)
6      [0.0, 10.0)
7     [10.0, 20.0)
8     [30.0, 40.0)
9      [0.0, 10.0)
10    [20.0, 30.0)
11     [0.0, 10.0)
12    [10.0, 20.0)
13    [10.0, 20.0)
14    [30.0, 40.0)
15    [10.0, 20.0)
16     [0.0, 10.0)
17     [0.0, 10.0)
18    [10.0, 20.0)
19    [10.0, 20.0)
20     [0.0, 10.0)
21     [0.0, 10.0)
22     [0.0, 10.0)
23    [10.0, 20.0)
24     [0.0, 10.0)
25     [0.0, 10.0)
26    [50.0, 95.0)
27    [50.0, 95.0)
Name: V2, dtype: category
Categories (6, interval[int64, left]): [[0, 10) < [10, 20) < [20, 30) < [30, 40) < [40, 50) < [50, 95)]

## 1.8 窗格移动(shift)
就是整体的数据向上移动一个，适用场景：
1. 计算移动平均线
2. 计算移动标准差
3. 比如日期，要计算前一天和这一天的差值

In [28]:
display(data['V2'],data['V2'].shift)

0     95
1      9
2      5
3      4
4      3
5     13
6      4
7     18
8     31
9      8
10    23
11     4
12    17
13    14
14    34
15    18
16     4
17     1
18    12
19    10
20     2
21     5
22     1
23    10
24     3
25     5
26    63
27    79
Name: V2, dtype: int64

<bound method NDFrame.shift of 0     95
1      9
2      5
3      4
4      3
5     13
6      4
7     18
8     31
9      8
10    23
11     4
12    17
13    14
14    34
15    18
16     4
17     1
18    12
19    10
20     2
21     5
22     1
23    10
24     3
25     5
26    63
27    79
Name: V2, dtype: int64>