# 1 Pandas事件学列与日期

In [183]:
import datetime
import pandas as pd
import numpy as np

## 1.1时间构造函数
### 1.1.1 pandas构造时间的函数
pandas与datetime（）与python的datetime模块一致

In [184]:
now = datetime.datetime.now()
now.year,now.month,now.day,now.hour,now.minute,now.second

(2026, 1, 24, 17, 37, 58)

In [185]:
now.strftime('%Y-%m-%d %H:%M:%S')

'2026-01-24 17:37:58'

### 时间戳pd.Timestamp()和时间间隔pd.Period()
时间戳是最基本的时间序列数据，用于把数值与时点关联在一起。Pandas对象通过时间戳调用时点数据。

In [186]:
ts = pd.date_range('2023-01-01 12:00:00', periods=3, freq='D')
ts

DatetimeIndex(['2023-01-01 12:00:00', '2023-01-02 12:00:00',
               '2023-01-03 12:00:00'],
              dtype='datetime64[ns]', freq='D')

In [187]:
ts + 1*ts.freq

DatetimeIndex(['2023-01-02 12:00:00', '2023-01-03 12:00:00',
               '2023-01-04 12:00:00'],
              dtype='datetime64[ns]', freq='D')

In [188]:
# 这是最常见的


# 创建带日频率的时间周期
pr = pd.Period('2023-01-01', freq='D')
print(pr)  # 输出：2023-01-01
# 可以转换为Timestamp（取周期的起始时间）
ts_from_pr = pr.to_timestamp()
print(ts_from_pr)  # 输出：2023-01-01 00:00:00

2023-01-01
2023-01-01 00:00:00

In [189]:
pr +1

Period('2023-01-02', 'D')

In [190]:
data = [pd.Timestamp('2023-01-01 12:00:00'),
        pd.Timestamp('2023-01-02 12:00:00'),
        pd.Timestamp('2023-01-03 12:00:00')]
ts = pd.Series(np.random.random(3), index=data)
ts

2023-01-01 12:00:00    0.021060
2023-01-02 12:00:00    0.217287
2023-01-03 12:00:00    0.345965
dtype: float64

In [191]:
ts.index

DatetimeIndex(['2023-01-01 12:00:00', '2023-01-02 12:00:00',
               '2023-01-03 12:00:00'],
              dtype='datetime64[ns]', freq=None)

In [192]:
data1 = [pd.Period('2023-01-01 12:00:00'),
        pd.Period('2023-01-02 12:00:00'),
        pd.Period('2023-01-03 12:00:00')]
ts1 = pd.Series(np.random.random(3), index=data1)
ts1

2023-01-01 12:00:00    0.699856
2023-01-02 12:00:00    0.734225
2023-01-03 12:00:00    0.768701
Freq: s, dtype: float64

In [193]:
ts1.index

PeriodIndex(['2023-01-01 12:00:00', '2023-01-02 12:00:00',
             '2023-01-03 12:00:00'],
            dtype='period[s]')

### 1.1.3 构造时间序列date_range\bdate_range()
- 实际工作中，经常要生成含大量时间戳的超长索引一，一个个输入时间戳又枯燥，又低效
- 如果时间戳是定频的，用date_range（与bdate_range（）函数即可创Datetimelndex。
- date_range默认的频率是日历日，bdate_range的默认频率是工作日

In [194]:
pd.date_range('2008-01-01', '2023-01-03',freq='3M')

C:\Users\35796\AppData\Local\Temp\ipykernel_27992\3305013923.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range('2008-01-01', '2023-01-03',freq='3M')

DatetimeIndex(['2008-01-31', '2008-04-30', '2008-07-31', '2008-10-31',
               '2009-01-31', '2009-04-30', '2009-07-31', '2009-10-31',
               '2010-01-31', '2010-04-30', '2010-07-31', '2010-10-31',
               '2011-01-31', '2011-04-30', '2011-07-31', '2011-10-31',
               '2012-01-31', '2012-04-30', '2012-07-31', '2012-10-31',
               '2013-01-31', '2013-04-30', '2013-07-31', '2013-10-31',
               '2014-01-31', '2014-04-30', '2014-07-31', '2014-10-31',
               '2015-01-31', '2015-04-30', '2015-07-31', '2015-10-31',
               '2016-01-31', '2016-04-30', '2016-07-31', '2016-10-31',
               '2017-01-31', '2017-04-30', '2017-07-31', '2017-10-31',
               '2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
               '2019-01-31', '2019-04-30', '2019-07-31', '2019-10-31',
               '2020-01-31', '2020-04-30', '2020-07-31', '2020-10-31',
               '2021-01-31', '2021-04-30', '2021-07-31', '2021-10-31',
               '2022-01-31', '2022-04-30', '2022-07-31', '2022-10-31'],
              dtype='datetime64[ns]', freq='3ME')

In [195]:
pd.bdate_range('2008-01-01', '2023-01-03',freq='y')

C:\Users\35796\AppData\Local\Temp\ipykernel_27992\4182004290.py:1: FutureWarning: 'y' is deprecated and will be removed in a future version, please use 'YE' instead.
  pd.bdate_range('2008-01-01', '2023-01-03',freq='y')

DatetimeIndex(['2008-12-31', '2009-12-31', '2010-12-31', '2011-12-31',
               '2012-12-31', '2013-12-31', '2014-12-31', '2015-12-31',
               '2016-12-31', '2017-12-31', '2018-12-31', '2019-12-31',
               '2020-12-31', '2021-12-31', '2022-12-31'],
              dtype='datetime64[ns]', freq='YE-DEC')

In [196]:
pd.date_range('2008-01-01',freq='3M',periods=100)

C:\Users\35796\AppData\Local\Temp\ipykernel_27992\3339123153.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range('2008-01-01',freq='3M',periods=100)

DatetimeIndex(['2008-01-31', '2008-04-30', '2008-07-31', '2008-10-31',
               '2009-01-31', '2009-04-30', '2009-07-31', '2009-10-31',
               '2010-01-31', '2010-04-30', '2010-07-31', '2010-10-31',
               '2011-01-31', '2011-04-30', '2011-07-31', '2011-10-31',
               '2012-01-31', '2012-04-30', '2012-07-31', '2012-10-31',
               '2013-01-31', '2013-04-30', '2013-07-31', '2013-10-31',
               '2014-01-31', '2014-04-30', '2014-07-31', '2014-10-31',
               '2015-01-31', '2015-04-30', '2015-07-31', '2015-10-31',
               '2016-01-31', '2016-04-30', '2016-07-31', '2016-10-31',
               '2017-01-31', '2017-04-30', '2017-07-31', '2017-10-31',
               '2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
               '2019-01-31', '2019-04-30', '2019-07-31', '2019-10-31',
               '2020-01-31', '2020-04-30', '2020-07-31', '2020-10-31',
               '2021-01-31', '2021-04-30', '2021-07-31', '2021-10-31',
               '2022-01-31', '2022-04-30', '2022-07-31', '2022-10-31',
               '2023-01-31', '2023-04-30', '2023-07-31', '2023-10-31',
               '2024-01-31', '2024-04-30', '2024-07-31', '2024-10-31',
               '2025-01-31', '2025-04-30', '2025-07-31', '2025-10-31',
               '2026-01-31', '2026-04-30', '2026-07-31', '2026-10-31',
               '2027-01-31', '2027-04-30', '2027-07-31', '2027-10-31',
               '2028-01-31', '2028-04-30', '2028-07-31', '2028-10-31',
               '2029-01-31', '2029-04-30', '2029-07-31', '2029-10-31',
               '2030-01-31', '2030-04-30', '2030-07-31', '2030-10-31',
               '2031-01-31', '2031-04-30', '2031-07-31', '2031-10-31',
               '2032-01-31', '2032-04-30', '2032-07-31', '2032-10-31'],
              dtype='datetime64[ns]', freq='3ME')

## 1.2 转换时间戳
### 1.2.1 to_datetime()
- to datetime函数用于转换字符串、纪元式及混合的日期Series或日期列表。转换的是Series时，
- 返回的是具有相同的索引的Series，日期时间列表则会被转换为Datetimelndex
- 用于将字符串转换为时间戳
- 可以指定时间格式
- 可以处理缺失值

In [197]:
date_series = pd.Series(['2005/11/23', '2010/12/31', 'Jul,31,2009', 'Feb 1,2020', '01-14-2012'])
date_series

0     2005/11/23
1     2010/12/31
2    Jul,31,2009
3     Feb 1,2020
4     01-14-2012
dtype: object

In [198]:
df = pd.DataFrame(pd.Series(['2005/11/23', '2010/12/31', 'Jul, 31, 2009', 'Feb 1,2020', '01-14-2012',None],name='date'))
df

            date
0     2005/11/23
1     2010/12/31
2  Jul, 31, 2009
3     Feb 1,2020
4     01-14-2012
5           None

In [199]:
df['values'] = np.random.randn(len(df))
df

            date    values
0     2005/11/23 -0.131785
1     2010/12/31 -1.413661
2  Jul, 31, 2009 -0.056262
3     Feb 1,2020  0.574424
4     01-14-2012 -0.981046
5           None  1.389138

In [200]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    5 non-null      object
 1   values  6 non-null      float64
dtypes: float64(1), object(1)
memory usage: 228.0+ bytes

In [201]:
# NaN和NaT都是空值，一个not a number另一个是not a time
df['date'] = pd.to_datetime(df['date'], format='mixed')
df

        date    values
0 2005-11-23 -0.131785
1 2010-12-31 -1.413661
2 2009-07-31 -0.056262
3 2020-02-01  0.574424
4 2012-01-14 -0.981046
5        NaT  1.389138

### 1.2.2 Datetimelndex构造
- Pandas还支持直接使用Datetimelndex构建时间序列:
- 创建Datetimelndex时，freq='infer'可自动推断索引的频率

In [202]:
pd.DatetimeIndex(data = ['2010-01-01','2018-01-03','2023-05-08'])

DatetimeIndex(['2010-01-01', '2018-01-03', '2023-05-08'], dtype='datetime64[ns]', freq=None)

In [203]:
time_index = pd.DatetimeIndex(data = ['2010-01-01','2010-01-03','2010-01-05'],freq='infer')
time_index

DatetimeIndex(['2010-01-01', '2010-01-03', '2010-01-05'], dtype='datetime64[ns]', freq='2D')

In [204]:
time_index[0]+ 1*time_index.freq

Timestamp('2010-01-03 00:00:00')

time_index = pd.PeriodIndex(data=['2010-01-01','2010-01-03','2010-01-05'],freq='2D')
time_index

## 1.2.3提供格式参数format
- 要实现精准转换，除了传递datetime字符串，还可以通过format参数来指定格式，指定此参数还可以加速转换速度。
- Y年m月d日H时M分S秒

In [205]:


from datetime import datetime

# 待解析的 datetime 字符串
datetime_str = "2026年01月23日15时30分45秒"

# 定义对应的格式（与字符串格式完全匹配）
format_pattern = "%Y年%m月%d日%H时%M分%S秒"

# 使用 strptime + format 参数进行精准转换
dt = datetime.strptime(datetime_str, format_pattern)

print(dt)  # 输出：2026-01-23 15:30:45

2026-01-23 15:30:45

### 1.2.4无效数据
- 不可解析时，默认值errors='raise'会触发错误：
- errors=ignore'返回原始输入：
- errors='coerce'把无法解析的数据转换为NaT，即不是时间（NotaTime）：

In [206]:
# 2012-12-31
# 2012年12月31号
# None
# 2012/12/12
# 上面的那种类型不是平常的类型。所以说，在转换的时候，需要指定errors='ignore'或者其他的参数。
pd.to_datetime(['2012/12/12','2012年12月31号',None,'asd'],errors='ignore')

C:\Users\35796\AppData\Local\Temp\ipykernel_27992\3205188305.py:6: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
  pd.to_datetime(['2012/12/12','2012年12月31号',None,'asd'],errors='ignore')

Index(['2012/12/12', '2012年12月31号', None, 'asd'], dtype='object')

In [207]:
# 使用率最高的
pd.to_datetime(['2012/12/12','2012年12月31号',None,'asd'],errors='coerce')

DatetimeIndex(['2012-12-12', 'NaT', 'NaT', 'NaT'], dtype='datetime64[ns]', freq=None)

In [208]:
def my_transform(x):
    if x is None:
        return None
    if x.endswith('号'):
        return pd.to_datetime(x.replace('号','日'),format='%Y年%m月%d日')
    else:
        return x

In [209]:
pd.Series(['2012/12/12','2012年12月31号',None,'asd']).map(my_transform)

0             2012/12/12
1    2012-12-31 00:00:00
2                   None
3                    asd
dtype: object

## 1.3索引访问
### 1.3.1 常规索引访问
Datetimelndex可以当作常规索引，支持选择、切片等方法。

In [210]:
rag=pd.date_range(start='2026-01-01',periods=31,freq='M')
rag

C:\Users\35796\AppData\Local\Temp\ipykernel_27992\24519750.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  rag=pd.date_range(start='2026-01-01',periods=31,freq='M')

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31',
               '2027-01-31', '2027-02-28', '2027-03-31', '2027-04-30',
               '2027-05-31', '2027-06-30', '2027-07-31', '2027-08-31',
               '2027-09-30', '2027-10-31', '2027-11-30', '2027-12-31',
               '2028-01-31', '2028-02-29', '2028-03-31', '2028-04-30',
               '2028-05-31', '2028-06-30', '2028-07-31'],
              dtype='datetime64[ns]', freq='ME')

In [211]:
ts=pd.Series(data=np.random.randn(31),index=rag)
ts

2026-01-31    0.171631
2026-02-28   -0.508178
2026-03-31   -0.324960
2026-04-30   -1.648832
2026-05-31    1.091597
2026-06-30   -1.381470
2026-07-31    0.652896
2026-08-31    0.598230
2026-09-30   -0.571380
2026-10-31    1.755481
2026-11-30    0.228733
2026-12-31   -0.724440
2027-01-31   -0.357505
2027-02-28   -1.399034
2027-03-31    0.029528
2027-04-30   -1.285651
2027-05-31    0.758193
2027-06-30    0.401730
2027-07-31    0.282419
2027-08-31   -1.500970
2027-09-30   -0.428893
2027-10-31   -0.594247
2027-11-30    0.992847
2027-12-31    0.174056
2028-01-31    1.075848
2028-02-29   -1.112788
2028-03-31   -0.018000
2028-04-30    1.045902
2028-05-31    2.464804
2028-06-30   -0.020912
2028-07-31   -0.372519
Freq: ME, dtype: float64

In [212]:
ts.index[0],ts.index[-1]

(Timestamp('2026-01-31 00:00:00'), Timestamp('2028-07-31 00:00:00'))

In [213]:
ts.index[:5]

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31'],
              dtype='datetime64[ns]', freq='ME')

### 1.3.2局部字符索引
- 能解析为时间戳的日期与字符串可以作为索引的参数:
- pandas为访问较长的时间序列提供了便捷方法，年、年月字符串均可:
- 带DatetimeIndex的DateFrame也支持这种切片方式。局部字符串是标签切片的一种形式，这种切片也包含截止时点，即，与日期匹配的时间也会包含在内:

In [214]:
# 吧时间当索引
ts['2026']

2026-01-31    0.171631
2026-02-28   -0.508178
2026-03-31   -0.324960
2026-04-30   -1.648832
2026-05-31    1.091597
2026-06-30   -1.381470
2026-07-31    0.652896
2026-08-31    0.598230
2026-09-30   -0.571380
2026-10-31    1.755481
2026-11-30    0.228733
2026-12-31   -0.724440
Freq: ME, dtype: float64

In [215]:
ts['2026':'2027']

2026-01-31    0.171631
2026-02-28   -0.508178
2026-03-31   -0.324960
2026-04-30   -1.648832
2026-05-31    1.091597
2026-06-30   -1.381470
2026-07-31    0.652896
2026-08-31    0.598230
2026-09-30   -0.571380
2026-10-31    1.755481
2026-11-30    0.228733
2026-12-31   -0.724440
2027-01-31   -0.357505
2027-02-28   -1.399034
2027-03-31    0.029528
2027-04-30   -1.285651
2027-05-31    0.758193
2027-06-30    0.401730
2027-07-31    0.282419
2027-08-31   -1.500970
2027-09-30   -0.428893
2027-10-31   -0.594247
2027-11-30    0.992847
2027-12-31    0.174056
Freq: ME, dtype: float64

In [216]:
AAPL = pd.read_csv('users_all.csv')
AAPL.head()

,user_id,register_time,recently_logged,number_of_classes_join,number_of_classes_out,learn_time,school,is_school_filled,register_logged_time,register_now_time,logged_now_time,number_of_classes_now,number_of_courses_selected,login_time,login_place,time_difference_1,country,province,region
0,孙建乐,2022-06-17,2021-09-25,1,0,1667.28,NaN,0,-266 days,1 days,1 days,1,1.0,2021-09-25,中国广东广州,267 days,中国,广东,广州
1,何林,2022-06-17,2022-06-15,1,0,2109.75,NaN,0,-2 days,1 days,1 days,1,6.0,2022-03-10,中国山西吕梁,100 days,中国,山西,吕梁
2,李风,2022-06-17,2022-06-17,1,0,0.00,NaN,0,0 days,1 days,1 days,1,2.0,2022-06-17,中国贵州贵阳,1 days,中国,贵州,贵阳
3,吴风,2022-06-17,2022-06-15,1,0,10348.62,NaN,0,-2 days,1 days,1 days,1,1.0,2022-06-08,中国广东佛山,10 days,中国,广东,佛山
4,赵凤乐,2022-06-17,2022-06-08,1,0,9054.72,NaN,0,-9 days,1 days,1 days,1,1.0,2022-06-08,中国陕西,10 days,中国,陕西,NaN

In [217]:
AAPL['register_time'] = pd.to_datetime(AAPL['register_time'], format='mixed',errors='coerce')
AAPL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43983 entries, 0 to 43982
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user_id                     43983 non-null  object
 1   register_time               43981 non-null  datetime64[ns]
 2   recently_logged             43983 non-null  object
 3   number_of_classes_join      43983 non-null  int64
 4   number_of_classes_out       43983 non-null  int64
 5   learn_time                  43983 non-null  float64
 6   school                      10571 non-null  object
 7   is_school_filled            43983 non-null  int64
 8   register_logged_time        43983 non-null  object
 9   register_now_time           43983 non-null  object
 10  logged_now_time             43983 non-null  object
 11  number_of_classes_now       43983 non-null  int64
 12  number_of_courses_selected  191 non-null    float64
 13  login_time                  42692 non-null  object
 14  login_place                 42692 non-null  object
 15  time_difference_1           42692 non-null  object
 16  country                     42692 non-null  object
 17  province                    41859 non-null  object
 18  region                      31551 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(4), object(12)
memory usage: 6.4+ MB

In [218]:
AAPL.set_index('register_time', inplace=True)
AAPL.head()

,user_id,recently_logged,number_of_classes_join,number_of_classes_out,learn_time,school,is_school_filled,register_logged_time,register_now_time,logged_now_time,number_of_classes_now,number_of_courses_selected,login_time,login_place,time_difference_1,country,province,region
register_time,,,,,,,,,,,,,,,,,,
2022-06-17,孙建乐,2021-09-25,1,0,1667.28,NaN,0,-266 days,1 days,1 days,1,1.0,2021-09-25,中国广东广州,267 days,中国,广东,广州
2022-06-17,何林,2022-06-15,1,0,2109.75,NaN,0,-2 days,1 days,1 days,1,6.0,2022-03-10,中国山西吕梁,100 days,中国,山西,吕梁
2022-06-17,李风,2022-06-17,1,0,0.00,NaN,0,0 days,1 days,1 days,1,2.0,2022-06-17,中国贵州贵阳,1 days,中国,贵州,贵阳
2022-06-17,吴风,2022-06-15,1,0,10348.62,NaN,0,-2 days,1 days,1 days,1,1.0,2022-06-08,中国广东佛山,10 days,中国,广东,佛山
2022-06-17,赵凤乐,2022-06-08,1,0,9054.72,NaN,0,-9 days,1 days,1 days,1,1.0,2022-06-08,中国陕西,10 days,中国,陕西,NaN

## 1.5pandas对象的dt属性
Series对象和DataFrame的列数据提供了dt属性接口(accessors)，对应日期时间数据，通过这个接口可以快速实现特定的功能，非常快捷。

In [224]:
ts2 = pd.Timestamp('2022-06-01')
ts2.year,ts2.month,ts2.day

(2022, 6, 1)

In [226]:
AAPL.index

DatetimeIndex(['2022-06-17', '2022-06-17', '2022-06-17', '2022-06-17',
               '2022-06-17', '2022-06-17', '2022-06-17', '2022-06-16',
               '2022-06-16', '2022-06-15',
               ...
               '2020-09-18', '2020-09-18', '2020-09-18', '2020-09-18',
               '2020-09-11', '2020-09-11', '2020-09-10', '2020-09-10',
               '2020-09-04', '2020-09-03'],
              dtype='datetime64[ns]', name='register_time', length=43983, freq=None)

In [229]:
AAPL = pd.read_csv('users_all.csv')
AAPL['register_time'] = pd.to_datetime(AAPL['register_time'],errors='coerce',format='%Y-%m-%d')
AAPL['register_time'].dt.year

0        2022.0
1        2022.0
2        2022.0
3        2022.0
4        2022.0
          ...
43978    2020.0
43979    2020.0
43980    2020.0
43981    2020.0
43982    2020.0
Name: register_time, Length: 43983, dtype: float64

In [230]:
AAPL['register_time'].dt.is_month_start

0        False
1        False
2        False
3        False
4        False
         ...
43978    False
43979    False
43980    False
43981    False
43982    False
Name: register_time, Length: 43983, dtype: bool

## 1.6重采样（每几年做求和）
- Pandas有一个虽然简单，但却强大、高效的功能，可在频率转换时执行重采样，如，将秒数据转换为5分钟数据，这种操作在金融等领域里的应用非常广泛。
- resample()是基于时间的分组操作，每个组都遵循归纳方法。
- 从0.18.0版开始,resample()可以直接用于DataFrameGroupBy对象
> 注意:重采样一定要以时间类型做Index
- resample函数非常灵活，可以指定多种频率转换与重采样参数。
- 支持聚合函数的处理如:sum、mean、std、sem、max、min、mid、median

In [236]:
AAPL1 = AAPL.set_index('register_time')
AAPL1

,user_id,recently_logged,number_of_classes_join,number_of_classes_out,learn_time,school,is_school_filled,register_logged_time,register_now_time,logged_now_time,number_of_classes_now,number_of_courses_selected,login_time,login_place,time_difference_1,country,province,region
register_time,,,,,,,,,,,,,,,,,,
2022-06-17,孙建乐,2021-09-25,1,0,1667.28,NaN,0,-266 days,1 days,1 days,1,1.0,2021-09-25,中国广东广州,267 days,中国,广东,广州
2022-06-17,何林,2022-06-15,1,0,2109.75,NaN,0,-2 days,1 days,1 days,1,6.0,2022-03-10,中国山西吕梁,100 days,中国,山西,吕梁
2022-06-17,李风,2022-06-17,1,0,0.00,NaN,0,0 days,1 days,1 days,1,2.0,2022-06-17,中国贵州贵阳,1 days,中国,贵州,贵阳
2022-06-17,吴风,2022-06-15,1,0,10348.62,NaN,0,-2 days,1 days,1 days,1,1.0,2022-06-08,中国广东佛山,10 days,中国,广东,佛山
2022-06-17,赵凤乐,2022-06-08,1,0,9054.72,NaN,0,-9 days,1 days,1 days,1,1.0,2022-06-08,中国陕西,10 days,中国,陕西,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-11,徐军,2020-09-11,0,0,0.00,NaN,0,0 days,646 days,646 days,0,NaN,2020-06-17,中国湖南,1 days,中国,湖南,NaN
2020-09-10,刘军林,2020-06-15,9,5,2116.15,NaN,0,644 days,647 days,647 days,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-10,王志,2020-06-05,4,0,341.20,NaN,0,634 days,647 days,647 days,4,NaN,2020-06-08,中国河南驻马店,10 days,中国,河南,驻马店
2020-09-04,胡林林,2020-06-18,2,1,370.35,NaN,0,653 days,653 days,653 days,1,NaN,2020-02-25,中国河北保定,114 days,中国,河北,保定
2020-09-03,孙东,2020-11-04,0,0,0.00,NaN,0,62 days,654 days,654 days,0,NaN,2020-03-10,中国河南平顶山,100 days,中国,河南,平顶山

In [239]:
AAPL['register_year'] = AAPL['register_time'].dt.year
AAPL

,user_id,register_time,recently_logged,number_of_classes_join,number_of_classes_out,learn_time,school,is_school_filled,register_logged_time,register_now_time,logged_now_time,number_of_classes_now,number_of_courses_selected,login_time,login_place,time_difference_1,country,province,region,register_year
0,孙建乐,2022-06-17,2021-09-25,1,0,1667.28,NaN,0,-266 days,1 days,1 days,1,1.0,2021-09-25,中国广东广州,267 days,中国,广东,广州,2022.0
1,何林,2022-06-17,2022-06-15,1,0,2109.75,NaN,0,-2 days,1 days,1 days,1,6.0,2022-03-10,中国山西吕梁,100 days,中国,山西,吕梁,2022.0
2,李风,2022-06-17,2022-06-17,1,0,0.00,NaN,0,0 days,1 days,1 days,1,2.0,2022-06-17,中国贵州贵阳,1 days,中国,贵州,贵阳,2022.0
3,吴风,2022-06-17,2022-06-15,1,0,10348.62,NaN,0,-2 days,1 days,1 days,1,1.0,2022-06-08,中国广东佛山,10 days,中国,广东,佛山,2022.0
4,赵凤乐,2022-06-17,2022-06-08,1,0,9054.72,NaN,0,-9 days,1 days,1 days,1,1.0,2022-06-08,中国陕西,10 days,中国,陕西,NaN,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43978,徐军,2020-09-11,2020-09-11,0,0,0.00,NaN,0,0 days,646 days,646 days,0,NaN,2020-06-17,中国湖南,1 days,中国,湖南,NaN,2020.0
43979,刘军林,2020-09-10,2020-06-15,9,5,2116.15,NaN,0,644 days,647 days,647 days,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020.0
43980,王志,2020-09-10,2020-06-05,4,0,341.20,NaN,0,634 days,647 days,647 days,4,NaN,2020-06-08,中国河南驻马店,10 days,中国,河南,驻马店,2020.0
43981,胡林林,2020-09-04,2020-06-18,2,1,370.35,NaN,0,653 days,653 days,653 days,1,NaN,2020-02-25,中国河北保定,114 days,中国,河北,保定,2020.0
43982,孙东,2020-09-03,2020-11-04,0,0,0.00,NaN,0,62 days,654 days,654 days,0,NaN,2020-03-10,中国河南平顶山,100 days,中国,河南,平顶山,2020.0

In [243]:
# 每三个月对学习时间（learn_time）求平均值
AAPL1.resample('3M')['learn_time'].mean()

C:\Users\35796\AppData\Local\Temp\ipykernel_27992\3367680002.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  AAPL1.resample('3M')['learn_time'].mean()

register_time
2019-01-31     202.356304
2019-04-30     303.552016
2019-07-31     307.585208
2019-10-31     237.912722
2020-01-31    1047.167554
2020-04-30    1159.573888
2020-07-31            NaN
2020-10-31     890.154074
2021-01-31     601.068322
2021-04-30       1.997632
2021-07-31       0.005890
2021-10-31     688.406206
2022-01-31     463.431808
2022-04-30     134.834264
2022-07-31     553.119971
2022-10-31      14.774286
2023-01-31      47.948750
Name: learn_time, dtype: float64

## 时间差
Timedelta（）支持用多种参数生成时间差
- 时间差类型是完全兼容时间之间的计算的，两个时间的差值就是我们的时间差类型

In [244]:
now = pd.Timestamp.now()
now

Timestamp('2026-01-24 19:55:05.331554')

In [246]:
delta = pd.Timedelta('4 day')
delta

Timedelta('4 days 00:00:00')

In [247]:
future = now + delta
future

Timestamp('2026-01-28 19:55:05.331554')

In [248]:
delta = pd.Timedelta(days=1,seconds=10)
delta

Timedelta('1 days 00:00:10')

In [249]:
now+delta

Timestamp('2026-01-25 19:55:15.331554')

In [250]:
s = pd.Series(pd.date_range(now,periods=3,freq='D'))
td = pd.Series(pd.timedelta_range('1 day','3 day'))
df = pd.DataFrame({'日期':s,'时间差':td})
df

                          日期    时间差
0 2026-01-24 19:55:05.331554 1 days
1 2026-01-25 19:55:05.331554 2 days
2 2026-01-26 19:55:05.331554 3 days

In [251]:
df['新日期'] = df['日期'] + df['时间差']
df

                          日期    时间差                        新日期
0 2026-01-24 19:55:05.331554 1 days 2026-01-25 19:55:05.331554
1 2026-01-25 19:55:05.331554 2 days 2026-01-27 19:55:05.331554
2 2026-01-26 19:55:05.331554 3 days 2026-01-29 19:55:05.331554

In [ ]:
df['新日期']-df['日期']

0   1 days
1   2 days
2   3 days
dtype: timedelta64[ns]

: